### ISSUE TITLE
Missing Module

### ISSUE THREAD

**Issue by danieldahan** [iwatakeshi/koa-jade-render#1]
Tried your module and I get this error:

Error: Cannot find module 'character-parser'

**Comment by iwatakeshi** [comment]
@danieldahan Thanks for the report! I wonder where character parser is coming from since `koa-jade-parser` doesn't use any character parser. I'll look into it later today though. In the mean time if you do see an issue and think you can fix it then I'll be glad to accept a pull request. :)

**Comment by danieldahan** [comment]
I should have copied the file, it was coming from the jade package I believe. After playing with it some more, I found an issue with the router and render and seem to have it working now :) I will close this for now.
